language: java

script:
  - mvn -Prun-its clean install

install: /bin/true

after_failure:
  - find target/it -name *.log -exec echo {} \; -exec cat {} \;

jdk:
  - oraclejdk8

branches:
    except:
        - gh-pages

notifications:
  email:
    - matthieu@brouillard.fr
